### ISSUE TITLE
VPN 模式无法连接redis

### ISSUE THREAD

**Issue by wajncn** [gejun123456/redispluginIssues#31]
VPN 模式无法连接redis
使用RDM可以正常连接

**Comment by wajncn** [comment]
io.lettuce.core.RedisConnectionException: Unable to connect to 172.17.16.115:6379
	at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:78)
	at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:56)
	at io.lettuce.core.AbstractRedisClient.getConnection(AbstractRedisClient.java:295)
	at io.lettuce.core.RedisClient.connect(RedisClient.java:214)
	at org.bruce.tools.nosql.b.b.g.a(g.java:333)
	at org.bruce.tools.nosql.b.b.c.a(c.java:46)
	at org.bruce.tools.nosql.c.e.M.run(M.java:161)

**Comment by wajncn** [comment]
![Uploading image.png…]()

**Comment by wajncn** [comment]
![Uploading image.png…]()

**Comment by gejun123456** [comment]
加我qq 1098632410 来远程看看

**Comment by gejun123456** [comment]
[RedisNew-2021.03.09.zip](https://github.com/gejun123456/redispluginIssues/files/6114473/RedisNew-2021.03.09.zip)
试试这个版本，谢谢
