### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by gejun123456** [gejun123456/redispluginIssues#48]
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'serviceClass' of com/intellij/openapi/components/ServiceManager.getService must not be null
 at com.intellij.openapi.components.ServiceManager.$$$reportNull$$$0(ServiceManager.java)
 at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java)
 at org.bruce.tools.nosql.j.a(j.java:52)
 at org.bruce.tools.nosql.j.a(j.java:62)
 at org.bruce.tools.nosql.o.o(o.java:126)
 at org.bruce.tools.nosql.n.run(n.java:106)
 at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
 at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
 at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
 at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
 at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:513)
 at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:75)
 at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:118)
 at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
 at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
 at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
 at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
 at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
 at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
 at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
 at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
 at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
 at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
 at com.intellij.ide.IdeEventQueue.lambda

**Comment by gejun123456** [comment]
will fix in next version.
