### ISSUE TITLE
format: host:port in error message

### ISSUE THREAD

**Issue by BSVogler** [gejun123456/redispluginIssues#49]
I am trying to figure out why I cannot connect.
I enter the server hostname with the port in the format host:port.
Then I get an error message

> io.lettuce.core.RedisConnectionException: Unable to connect to **host/ :20185** at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:78)…

The format I marked in bold here is different from what is entered. Is there a bug?

**Comment by gejun123456** [comment]
what is your configuration like? have you use ssh or ssl?  I have checkd my local server and azure cache it works.

**Comment by gejun123456** [comment]
when i use the wrong port, there is a error 
![image](https://user-images.githubusercontent.com/6340473/182612099-b7d1a308-4ebd-4646-b18b-6e9122c006ef.png)
could you share your redis server version so i can check it.

**Comment by BSVogler** [comment]
I use ssl over an external provided ssh port forwarding.

When using the redisplugin's internal I get

> io.lettuce.core.RedisConnectionException: Unable to connect to localhost/127.0.0.1:51027 at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:78)

The redis server runs 6.2

**Comment by gejun123456** [comment]
[RedisNew-2022.08.04.zip](https://github.com/gejun123456/redispluginIssues/files/9268645/RedisNew-2022.08.04.zip)
could you help try this version to see if it works.

**Comment by gejun123456** [comment]
are you using redis cluster?

**Comment by BSVogler** [comment]
Not using redis cluster.

**Comment by BSVogler** [comment]
Again running into this error. Manually using ssh and then redis-cli works fine. When using redis explorer I get this

> io.lettuce.core.RedisConnectionException: Unable to connect to localhost/127.0.0.1:62330 at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:78) at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:56) at i...
