### ISSUE TITLE
NullPointerException when refreshing expired item

### ISSUE THREAD

**Issue by BohdanM-AVISPL** [gejun123456/redispluginIssues#50]
![image](https://user-images.githubusercontent.com/90767530/185488807-b735eb2e-e18a-4416-89ee-be63883be0e9.png)

When I click refresh button. This item was actually removed from redis.

```
kotlin.KotlinNullPointerException 
at org.bruce.tools.nosql.a.d.q.a(q.java:141) 
at org.bruce.tools.nosql.f.e.L.a(L.java:120) 
at org.bruce.tools.nosql.f.b.s.a(s.java:40) 
at org.bruce.tools.nosql.f.b.s.access$000(s.java:18) 
at org.bruce.tools.nosql.f.b.x.a(x.java:34) 
at org.bruce.tools.nosql.f.e.l.run(l.java:179) 
at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442) 
at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114) 
at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:493) 
at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:244) 
at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:189) 
at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608) 
at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683) 
at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639) 
at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607) 
at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60) 
at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:176) 
at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:244) 
at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) 
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) 
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) 
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668) 
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665) 
at java.base/java.security.AccessController.doPrivileged(Native Method) 
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665) 
at java.base/java.lang.Thread.run(Thread.java:829)
```

Expected behavior:

Show: Item already deleted.

**Comment by BohdanM-AVISPL** [comment]
@gejun123456 
Why it is `[enhancement]` if it is a bug?!

**Comment by gejun123456** [comment]
you are right， will fix it soon

**Comment by gejun123456** [comment]
thanks for reporing thanks for reporting [RedisNew-2023.04.14.zip](https://github.com/gejun123456/redispluginIssues/files/11232750/RedisNew-2023.04.14.zip) will fix the issue.
